### ISSUE TITLE
Powershell Erreur

### ISSUE THREAD

**Issue by BenFaure** [GeoHolz/SysAdmin#1]
Bonjour,

Je rencontre un problème avec votre script.

Voici le message d'erreur lors du lancement.

Pouvez-vous m'aider ?

```
Exception lors de l'appel de «Send» avec «1» argument(s): «Boîte aux lettres non disponible. La réponse du serveur
était: 5.1.1 User unknown»
Au caractère C:\Users\bfaure\Desktop\Password_Expire.ps1:248 : 1
+ $mailSysadmin.Send($messageSysAdmin)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SmtpFailedRecipientException
```

**Comment by GeoHolz** [comment]
As tu précisé les variables $smtpfromSysadmin et $smtptoSysadmin ?
Ligne 50 et 51

**Comment by BenFaure** [comment]
Oui, c'est précisé. Cependant, lorsque j’enlève le testing et TestRecipient je n'ai plus d'erreurs.

Mais les utilisateurs ne semble pas recevoir d'emails

**Comment by GeoHolz** [comment]
Peux tu me donner la commande que tu exécutes ?

**Comment by BenFaure** [comment]
.\Password_Expire.ps1 -smtpServer mxe.us.xxxx.local -expireInDays 3 -from adresse@email.com -Logging -LogPath "c:\log"
Avec celle ci je n'ai pas d'erreur mais aucun mail n'est reçu.

.\Password_Expire.ps1 -smtpServer mxe.us.xxx.local -expireInDays 3 -from it@mail.com -Logging -LogPath "c:\log" -testing -testRecipient monadresse@mail.com

Sur lequel j'avais le message d'erreur que je n'ai plus désormais. Mais aucun mail n'est reçu. Ni moi ni les utilisateurs

EDIT : J'ai écris trop vite, les mails arrivent avec un peu de retard sur mon outlook avec la seconde commande (environ 2-3 minutes après la fin de la commande)

**Comment by GeoHolz** [comment]
Il te reste quoi comme erreur alors ? Pas d'email avec la 1er commande ?
Est ce que les adresses mails des utilisateurs sont bien renseignés dans leurs compte AD ? Auto si Exchange

**Comment by BenFaure** [comment]
Finalement, je n'ai plus d'erreurs, j'ai passé le script sur un serveur au lieu de mon PC et il semble fonctionner. 
Oui les e-mails sont renseignés pour OF365.
Par contre, en mode test, on reçoit juste le tableau récapitulatif, on ne reçoit pas les e-mails qui devraient être adresser aux utilisateurs ?

**Comment by GeoHolz** [comment]
Si, tu es censé les recevoir à la place des utilisateurs

**Comment by BenFaure** [comment]
Je les ai reçu qu'une seule fois. La commande est bien celle-ci : 

`.\Password_Expire.ps1 -smtpServer dmxe.us.company.local -expireInDays 14 -from it@ent.com -Logging -LogPath "c:\log" -testing -testRecipient nom.prenom@mail.com`

Je pense que le blocage vient plutot du serveur SMTP
